services:
  client:
    build: .
    container_name: exploding-kittens-client
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - proxy
    restart: unless-stopped
    env_file:
      - stack.env

  server:
    build: .
    container_name: exploding-kittens-server
    ports:
      - "8000:8000"
    command: npm run serve
    networks:
      - proxy
    restart: unless-stopped
    env_file:
      - stack.env

networks:
  proxy:
    external: true
