services:
  client:
    build: .
    container_name: exploding-kittens-client
    ports:
      - "1234:1234"
    command: npm start
    networks:
      - proxy

  server:
    build: .
    container_name: exploding-kittens-server
    ports:
      - "8000:8000"
    command: npm run serve
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
